version: "3.7"
services:
  fonyou-mongo:
    image: mongo
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Test123
    ports: 
    - "27017:27017"
    volumes: 
      - fonyou-mongo-data:/etc/mongo
    networks: 
      - backend
  
  app:
    build: 
      context: finaltest
      dockerfile: Dockerfile
    ports: 
      - "80:8080"
    restart: always
    depends_on:
      - fonyou-mongo
    volumes: 
      - fonyou-app:/opt
    environment: # Pass environment variables to the service
      SPRING_DATA_MONGODB_URI: mongodb://root:Test123@fonyou-mongo:27017/fonyou-mongo?ssl=false&authSource=admin&authMechanism=SCRAM-SHA-1
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      BUSINESS_PROPERTIES_FILE_NAME: /Users/alvaroagudelo/Documents/sirius.properties
      # MAIN_MESSAGE_OKMSG: "Mensaje super exitoso desde docker compose"
      # MAIN_MESSAGE_FAILEDMSG: "Mensaje super mega pailas, suerte desde docker compose"
      # SPRING_DATASOURCE_URL: jdbc:mysql://fonyou-mysql:3306/fonyou?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      # SPRING_DATASOURCE_URL: mongodb://root:Test123@fonyou-mongo:27017/fonyou-mongo
      # SPRING_DATASOURCE_USERNAME: root
      # SPRING_DATASOURCE_PASSWORD: Test123
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

volumes:
  fonyou-mongo-data:
  fonyou-app:

networks: 
  backend: