version: '3.7'
services:
  fonyou-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: fonyou
      MYSQL_ROOT_PASSWORD: Test123
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3307:3306"
    volumes:
      - fonyou-data:/var/lib/mysql
    networks: 
      - backend
  
  app:
    build: 
      context: finaltest
      dockerfile: Dockerfile
    ports: 
      - "80:8080"
    restart: always
    depends_on:
      - fonyou-mysql
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://fonyou-mysql:3306/fonyou?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test123
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

volumes:
  fonyou-data:

networks: 
  backend: