version: '3.1'
services:
  fonyou-mysql:
   container_name: fonyou-mysql
   image: mysql
   environment:
    MYSQL_DATABASE: fonyou
    MYSQL_ROOT_PASSWORD: Nexus123
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   volumes:
      - fonyou-data:/var/lib/mysql
  
  app:
    build: ./finaltest
    working_dir: /finaltest
    volumes:
      - ./finaltest:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    ports: 
      - "80:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - fonyou-mysql

volumes:
  fonyou-data: